spec-version: 0.30.0
name: preql
version: 0.5
synopsis: safe PostgreSQL queries using Quasiquoters
description: |
  Before you Post(gres)QL, preql.

  @preql@ provides an effect type class `SQL`, a `select` quasiquoter
  that checks SQL syntax at compile time, and a `sql` quasiquoter that
  supports variable antiquotes, but does not attempt syntax
  validation.

  For more details, read
  the [quickstart](https://github.com/bergey/preql#quickstart) 
  or the [vision](https://github.com/bergey/preql#vision-parsing-sql-in-haskell-quasiquotes)

  Most applications will want to import the top-level module @Preql@.  When writing @SQL@
  instances or your own higher-level abstractions, you may want the lower-level,
  IO-specific functions in @Preql.Wire@, not all of which are re-exported from @Preql@.
    
category: Database, PostgreSQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org
extra-doc-files:
  - CHANGELOG.md

library:
  source-dirs: [src]

tests:
  tests:
    source-dirs: test
    main: Test.hs
    dependencies:
      - preql
      - containers >= 0.6.2.1
      - generic-random
      - tasty >= 1.2.3
      - tasty-hunit >= 0.10.0
      - hedgehog >= 1.0.3
      - tasty-hedgehog >= 1.0

build-tools:
  - alex
  - happy
      
dependencies:
  - aeson >= 1.4.7.1
  - array >= 0.5.4.0
  - base >= 4.13.0.0
  - binary-parser >= 0.5.6
  - bytestring >= 0.10.10.0
  - bytestring-strict-builder >= 0.4.5.3
  - contravariant >= 1.5.2
  - mtl >= 2.2.2
  - postgresql-binary >= 0.12.2
  - postgresql-libpq >= 0.9.4.2
  - scientific >= 0.3.6.2
  - syb >= 0.7.1
  - template-haskell >= 2.15.0.0
  - text >= 1.2.3.2
  - th-lift-instances >= 0.1.17
  - time >= 1.9.3
  - transformers >= 0.5.6.2
  - unordered-containers
  - uuid >= 1.3.13
  - vector >= 0.12.1.2
  - vector-sized >= 1.4.1

default-extensions:
  - OverloadedStrings
  - DataKinds

benchmarks:
  pgbench:
    main: Bench.hs
    source-dirs:
      - benchmark
    dependencies:
      - preql
      - criterion
      - deepseq
