spec-version: 0.30.0
name: preql
version: 0.1
synopsis: safe PostgreSQL queries using Quasiquoters
description: |
  Before you Post(gres)QL, preql.

  @preql@ provides a low-level interface to PostgreSQL and a quasiquoter that converts
  inline variable names to SQL parameters.  Higher-level interfaces, checking SQL syntax &
  schema, are planned.

  the [quickstart](https://github.com/bergey/preql#quickstart) 
  or the [vision](https://github.com/bergey/preql#vision-parsing-sql-in-haskell-quasiquotes)

  Most applications will want to import the top-level module @Preql@.  When writing @SQL@
  instances or your own higher-level abstractions, you may want the lower-level,
  IO-specific functions in @Preql.Wire@, not all of which are re-exported from @Preql@.
    
category: Database, PostgreSQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org
extra-doc-files:
  - CHANGELOG.md

library:
  source-dirs: [src]

tests:
  tests:
    source-dirs: test
    main: Test.hs
    dependencies:
      - preql
      - bytestring
      - postgresql-libpq
      - tasty
      - tasty-hunit
      - text
      - uuid
      - vector

build-tools:
  - alex
  - happy
      
dependencies:
    - aeson >= 1.3.1
    - array >= 0.5.2
    - base >= 4.11 # GHC 8.4; need CPP semigroup/monoid to go earlier
    - binary-parser >= 0.5.5
    - bytestring >= 0.10.8
    - bytestring-strict-builder >= 0.4.5
    - contravariant >= 1.4.1
    - free >= 5.0.2
    - mtl >= 2.2.2
    - postgresql-binary >= 0.12.1
    - postgresql-libpq >= 0.9.4
    - scientific >= 0.3.6
    - template-haskell >= 2.13.0
    - text >= 1.2.3
    - th-lift-instances >= 0.1.11
    - time >= 1.8.0
    - transformers >= 0.5.5
    - uuid >= 1.3.13
    - vector >= 0.12.0

default-extensions:
  - OverloadedStrings
