spec-version: 0.30.0
name: preql-speed-test
version: 0.5
synopsis: speed test for preql
description: measures decoding speed
category: Database, PostgreSQL
github: bergey/preql
author: Daniel Bergey
maintainer: bergey@teallabs.org

dependencies:
  - aeson >= 1.4.7.1
  - array >= 0.5.4.0
  - base >= 4.13.0.0
  - binary-parser >= 0.5.6
  - bytestring >= 0.10.10.0
  - bytestring-strict-builder >= 0.4.5.3
  - contravariant >= 1.5.2
  - mtl >= 2.2.2
  - postgresql-binary >= 0.12.2
  - postgresql-libpq >= 0.9.4.2
  - scientific >= 0.3.6.2
  - syb >= 0.7.1
  - template-haskell >= 2.15.0.0
  - text >= 1.2.3.2
  - th-lift-instances >= 0.1.17
  - time >= 1.9.3
  - transformers >= 0.5.6.2
  - uuid >= 1.3.13
  - vector >= 0.12.1.2
  - vector-sized >= 1.4.1

default-extensions:
  - OverloadedStrings
  - DataKinds

executables:
  preql-speed:
    main: Speed.hs
    dependencies:
      - preql
      - deepseq
      - optparse-applicative
      - resource-pool
      - stm
    ghc-options: "-rtsopts -threaded -eventlog -O2 -fprof-auto -fprof-cafs -fexternal-interpreter"
